filesys:
  rootDir: data
  tempDir: data/temp
  testCaseDir: data/testcases
  testZipDir: data/zipExtraction
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj_db
    username: root
    #    driverClassName: org.postgresql.Driver
    #    url: jdbc:postgresql://localhost:5432/oj-db-postgresql
    #    username: postgres
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  #    database: postgresql
  security:
    enable-csrf: false

docker:
  image: code2
  mountFolder: docker_workspace
  workspace: workspace
jwt:
  secret: "00000000000000000000000000000000"
  expiration: 22896000000
  authHeader: "Authorization"

frontend:
  address: "http://localhost:3000"